Project setup
Meri-MG/Ruby-Group-Capstone pull request #48
Opened 2022-03-15 09:54 UTC by Meri-MG

In this PR was: 
- Set up the project with all necessary linters and Readme file
- Created Item class in a separate .rb file.
- All Item class properties visible in the diagram are defined and set up in the constructor method. 
- Added all methods visible in the diagram.
- Implemented methods:
can_be_archived?() in the Item class
move_to_archive() in the Item class

- Created a main.rb file that will serve as the console app entry-point.
- Implemented startup actions:
Present the user with a list of options to perform.
Let users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

2022-03-15 13:49 UTC, akucintavalent requested changes
# REQUESTED CHANGES

Good job so far, @Meri-MG 

- You have created a nice README.md file.
- You installed the necessary linters
- You have created a nice `main.rb` file
- You passed linter checks

## CHANGES TO BE DONE

- [ ] Please add a `MIT.md` file with the proper license to the project
- [ ] Check out the comments below

## SUGGESTIONS

- [ ] It is a good practice to give write (or read) permissions only whenever is needed because when an item is created we don't want to be able to change the `@id` or some other fields.

2022-03-15 13:49 UTC, akucintavalent commented on README.md
> +  ruby library.rb
It is better to use a more general filename like `ruby file_name.rb` or you can use `ruby main.rb`

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +class Item
You forgot to include 'date' module:
`require 'date'`

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    @id = id || Random.rand(1..100)
If you are going to always pass a truthy (not `nil` or `false`) value as `id` parameter, you don't need `Random.rand(1..100)` because it will never be used.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    @id = id || Random.rand(1..100)
[OPTIONAL] Just a suggestion: I think you should use a class variable that will contain the id of the last created element, and you should start from `0` or `1`, i.e.:

```
class Item
  @@id = 1
  def initialize(publish_date, archived: false)
    @id = @@id
    @@id += 1
    # ...
  end
  # ...
end
```

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    year >= 10
This is not a very precise way to check if 10 years have passed. Consider the following code:
```
irb(main):012:0> item1 = Item.new(6, "2012-03-30", archived: true)
=> #<Item:0x00007fc68c91f640 @id=6, @publish_date=#<Date: 2012-03-30 ((2455651j,0s,0n),+0s,2299161j)>, @archived=true>
irb(main):013:0> item1.can_be_archived?
=> true
irb(main):014:0> Date.today
=> #<Date: 2022-03-15 ((2459654j,0s,0n),+0s,2299161j)>
irb(main):015:0> 
```
As you can see here 10 years have not passed and `#can_be_archived?` should return `false`. Please take into account months and days.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +  attr_accessor :id, :publish_date, :archived
We should not have writing or reading permission for `id` and `archived` fields since the UML diagram shows that they should be 'private' by adding a minus in front of their names. Plus symbol in front of a field or method's name means that we should have (writing and reading) permissions (it should be public)
<img width="254" alt="Zrzut ekranu 2022-03-15 o 14 06 50" src="https://user-images.githubusercontent.com/87897753/158384206-f06426c5-b5d6-40e5-a68a-a49f2521dbd9.png">

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +puts new_item.move_to_archive
Kindly remove the above code from the file: the `development` branch should be as clean and as free from bugs as possible.

2022-03-15 13:49 UTC, akucintavalent commented on main.rb
> +      puts 'E'
[OPTIONAL] You don't need these two lines since you will never reach them.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +  def can_be_archived?
According to the UML diagram, this method should be private.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    label.items.push(self) unless label.items.include?(self)
According to the UML diagram, we don't have reading permissions of the `items` field. We should use the `add_item` method, inside of which we should handle the case when the `items` field contains the item.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    genre.add_item(self) unless genre.items.include?(self)
According to the UML diagram, we don't have reading/writing permissions of the `items` field. We should use the `add_item` method, inside of which we should handle the case when the `items` field contains the item.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    author.items.push(self) unless author.items.include?(self)
According to the UML diagram, we don't have reading permissions of the `items` field. We should use the `add_item` method, inside of which we should handle the case when the `items` field contains the item.

2022-03-15 13:49 UTC, akucintavalent commented on item.rb
> +    source.items.push(self) unless source.items.include?(self)
According to the UML diagram, we don't have reading permissions of the `items` field. We should use the `add_item` method, inside of which we should handle the case when the `items` field contains the item.

2022-03-15 14:35 UTC, Meri-MG commented on main.rb
> +      puts 'E'
I put the "break if" case on '0' so when the user enters 0 he will exit the app. puts 'E' was just to check if the case was working.

2022-03-15 14:40 UTC, Meri-MG commented on item.rb
> +    genre.add_item(self) unless genre.items.include?(self)
It's implemented here in a right way, isn't it?

2022-03-15 14:52 UTC, akucintavalent commented on item.rb
> +    genre.add_item(self) unless genre.items.include?(self)
I think `unless @items.include?(self)` must be inside the `genre.add_item` method

2022-03-16 10:14 UTC, akucintavalent approved these changes
# STATUS APPROVED

Good job, @Meri-MG. It is time to merge it.

2022-03-16 10:23 UTC, merged