Music branch
Meri-MG/Ruby-Group-Capstone pull request #51
Opened 2022-03-17 10:50 UTC by mwanawabangona

- [ ]  Created Music Class
- [ ] Created schema.sql
- [ ] Created unit tests
- [ ] Created preserve date through json

2022-03-17 18:07 UTC, akucintavalent requested changes
Hi @mwanawabangona 

Great job so far with your project. There are still a few issues that need to be dealt with.

## Required Changes ♻️ 

- [ ] Please create a folder called `MusicAlbums-Genres` and place folders `spec`, `classes`,`json_files`,`modules` inside of it. And please add the `schema.sql` file there too.
- [ ] Check out the comments below. 

Happy coding!

2022-03-17 18:07 UTC, akucintavalent commented on classes/genre.rb
> +    @id = id || Random.rand(1..1000)
You should use a class variable here like so:
```Ruby
class Genre
  @@id = 1
  def initialize(name)
    @id = @@id
    @@id += 1
  end
end
```
Our group has decided to do that because using random can make two ids have the same value, and passing id is not what we want.

2022-03-17 18:07 UTC, akucintavalent commented on classes/genre.rb
> +    @arr_i = []
Please change the name of that variable to @items because it is more readable and understandable. A varaible's name should aways carry its purpose in it.

2022-03-17 18:07 UTC, akucintavalent commented on classes/music_album.rb
> +    super(id, name, publish_date)
`id` variable is not defined here. Please use a class variable to create `id`s in `Item` class and don't pass id as an argument anywhere.
```Ruby
class Item
  @@id = 1
  def initialize(name)
    @id = @@id
    @@id += 1
  end
end
```

2022-03-17 18:07 UTC, akucintavalent commented on classes/music_album.rb
> +    super and @on_spotify
Please don't use `and` instead of `&&`. It does not follow the Ruby Guidelines

2022-03-17 18:07 UTC, akucintavalent commented on item.rb
> +  def initialize(_id, name, publish_date, archived: false)
You don't need to pass `id` or `name` here. Kindly remove those arguments from the method definition.

2022-03-17 18:07 UTC, akucintavalent commented on item.rb
> +    @name = name
You already add `@name` in the `MusicAlbum` class and the UML diagram doesn't require you to have a name field inside of the `Item` class. Please remove this line.

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +    @load_genres = []
The name of this variable should be just `genres` because names of variables should be nouns, not verbs (like functions).

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +
It would be much better if your code didn't contain commented code because it makes it not look clean.

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +    puts 'Album name: '
Please use `print` instead of puts here so that we could enter the name on the same line.

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +    puts 'Date of publish [Enter date in format (yyyy-mm-dd)]'
Please use `print` instead of `puts` here so that we could enter the date on the same line.

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +    puts 'Is it available on Spotify? Y/N'
Please use `print` instead of `puts` here so that we could enter Y/N on the same line.

2022-03-17 18:07 UTC, akucintavalent commented on main.rb
> +      list_all_genres
Please create a `json` file fille with a list of objects that represent genres. In the beginning of the running of the program, this list should be loaded and placed in the variable `@genres` (currently `@load_genres`)

2022-03-17 18:07 UTC, akucintavalent commented on modules/music_album_mule.rb
> +  def load_music_albums
You should create the `load_genres` function which would load data from a JSON file that contains a list of objects that represent genres.

2022-03-17 18:07 UTC, akucintavalent commented on schema.sql
> +-- CREATE TABLE books
Please remove these comments.

2022-03-17 18:07 UTC, akucintavalent commented on schema.sql
> +    label_id INT,
Please add the `source_id` column so that it corresponded to the UML diagram.

2022-03-17 18:07 UTC, akucintavalent commented on schema.sql
> +CREATE TABLE item (
In order to be more consistent please rename the table to `items` because other tables are named with plural names.

2022-03-17 18:07 UTC, akucintavalent commented on spec/music_album_spec.rb
> +  it 'music should be an instance of Music class' do
It would be better if you wrote test(s) with adding genre to a `music_album`

2022-03-17 18:07 UTC, akucintavalent commented on spec/music_album_spec.rb
> +require './classes/music_album'
Please write tests for the `Genre` class and don't forget to test adding `music_albums`

2022-03-17 18:46 UTC, mwanawabangona commented on spec/music_album_spec.rb
> +  it 'music should be an instance of Music class' do
done

2022-03-18 10:51 UTC, Meri-MG approved these changes
Hi, @mwanawabangona!
Good job working on the required changes!

Your part can be merged now!

2022-03-18 11:42 UTC, closed without merging